[package]
name = "adventofcode-2023"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10"
itertools = "0.12"
num = "0.4"
colored = "2.1"
priority-queue = "1.3.2"
rustworkx-core = "0.13.2"
